### ISSUE TITLE
change animation on hover of buttons

### ISSUE THREAD

**Issue by casafurix** [mlscvitpune/Portfolio-Template-using-React#10]

**Comment by yashthipsay** [comment]
Hi @AryanShinde, I want to work on this

**Comment by AryanShinde** [comment]
sure @yashthipsay you can work on it! Best of luck!

**Comment by Mayureshkaulwar** [comment]
I want to work on this project

**Comment by sanketdisale871** [comment]
I want to work on this issue. @AryanShinde

**Comment by AryanShinde** [comment]
You guys have another PR to work on. This issue is available for others to fix.

**Comment by SohamRatnaparkhi** [comment]
Hi, I would like to work on this issue.
Could you assign it to me.

**Comment by casafurix** [comment]
sure....good luck!
