### ISSUE TITLE
add animation on hover, for the cards in the Work section.

### ISSUE THREAD

**Issue by casafurix** [mlscvitpune/Portfolio-Template-using-React#8]

**Comment by AryanShinde** [comment]
Sure, please look the CONTRIBUTING.md file in the code section and follow the same to make a PR. We will provide a code of conduct of how we expect yout PR to be. So Best of luck!

**Comment by Akshay9607** [comment]
Hey , i made above mentioned changes , can you please review my pull request .

If any changes are to be made , please let me know .
